// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockservices_test

import (
	"context"

	"github.com/browningluke/opnsense-go/pkg/unbound"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOpnsenseClientAdapter creates a new instance of MockOpnsenseClientAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOpnsenseClientAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOpnsenseClientAdapter {
	mock := &MockOpnsenseClientAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOpnsenseClientAdapter is an autogenerated mock type for the OpnsenseClientAdapter type
type MockOpnsenseClientAdapter struct {
	mock.Mock
}

type MockOpnsenseClientAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOpnsenseClientAdapter) EXPECT() *MockOpnsenseClientAdapter_Expecter {
	return &MockOpnsenseClientAdapter_Expecter{mock: &_m.Mock}
}

// CreateHostOverride provides a mock function for the type MockOpnsenseClientAdapter
func (_mock *MockOpnsenseClientAdapter) CreateHostOverride(ctx context.Context, req *unbound.HostOverride) (string, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateHostOverride")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *unbound.HostOverride) (string, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *unbound.HostOverride) string); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *unbound.HostOverride) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOpnsenseClientAdapter_CreateHostOverride_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateHostOverride'
type MockOpnsenseClientAdapter_CreateHostOverride_Call struct {
	*mock.Call
}

// CreateHostOverride is a helper method to define mock.On call
//   - ctx context.Context
//   - req *unbound.HostOverride
func (_e *MockOpnsenseClientAdapter_Expecter) CreateHostOverride(ctx interface{}, req interface{}) *MockOpnsenseClientAdapter_CreateHostOverride_Call {
	return &MockOpnsenseClientAdapter_CreateHostOverride_Call{Call: _e.mock.On("CreateHostOverride", ctx, req)}
}

func (_c *MockOpnsenseClientAdapter_CreateHostOverride_Call) Run(run func(ctx context.Context, req *unbound.HostOverride)) *MockOpnsenseClientAdapter_CreateHostOverride_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *unbound.HostOverride
		if args[1] != nil {
			arg1 = args[1].(*unbound.HostOverride)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOpnsenseClientAdapter_CreateHostOverride_Call) Return(s string, err error) *MockOpnsenseClientAdapter_CreateHostOverride_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockOpnsenseClientAdapter_CreateHostOverride_Call) RunAndReturn(run func(ctx context.Context, req *unbound.HostOverride) (string, error)) *MockOpnsenseClientAdapter_CreateHostOverride_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteHostOverride provides a mock function for the type MockOpnsenseClientAdapter
func (_mock *MockOpnsenseClientAdapter) DeleteHostOverride(ctx context.Context, uuid string) error {
	ret := _mock.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for DeleteHostOverride")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, uuid)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOpnsenseClientAdapter_DeleteHostOverride_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteHostOverride'
type MockOpnsenseClientAdapter_DeleteHostOverride_Call struct {
	*mock.Call
}

// DeleteHostOverride is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *MockOpnsenseClientAdapter_Expecter) DeleteHostOverride(ctx interface{}, uuid interface{}) *MockOpnsenseClientAdapter_DeleteHostOverride_Call {
	return &MockOpnsenseClientAdapter_DeleteHostOverride_Call{Call: _e.mock.On("DeleteHostOverride", ctx, uuid)}
}

func (_c *MockOpnsenseClientAdapter_DeleteHostOverride_Call) Run(run func(ctx context.Context, uuid string)) *MockOpnsenseClientAdapter_DeleteHostOverride_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOpnsenseClientAdapter_DeleteHostOverride_Call) Return(err error) *MockOpnsenseClientAdapter_DeleteHostOverride_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOpnsenseClientAdapter_DeleteHostOverride_Call) RunAndReturn(run func(ctx context.Context, uuid string) error) *MockOpnsenseClientAdapter_DeleteHostOverride_Call {
	_c.Call.Return(run)
	return _c
}

// SearchHostOverrides provides a mock function for the type MockOpnsenseClientAdapter
func (_mock *MockOpnsenseClientAdapter) SearchHostOverrides(ctx context.Context) (*unbound.SearchHostOverrideResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SearchHostOverrides")
	}

	var r0 *unbound.SearchHostOverrideResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*unbound.SearchHostOverrideResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *unbound.SearchHostOverrideResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*unbound.SearchHostOverrideResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOpnsenseClientAdapter_SearchHostOverrides_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchHostOverrides'
type MockOpnsenseClientAdapter_SearchHostOverrides_Call struct {
	*mock.Call
}

// SearchHostOverrides is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockOpnsenseClientAdapter_Expecter) SearchHostOverrides(ctx interface{}) *MockOpnsenseClientAdapter_SearchHostOverrides_Call {
	return &MockOpnsenseClientAdapter_SearchHostOverrides_Call{Call: _e.mock.On("SearchHostOverrides", ctx)}
}

func (_c *MockOpnsenseClientAdapter_SearchHostOverrides_Call) Run(run func(ctx context.Context)) *MockOpnsenseClientAdapter_SearchHostOverrides_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOpnsenseClientAdapter_SearchHostOverrides_Call) Return(searchHostOverrideResponse *unbound.SearchHostOverrideResponse, err error) *MockOpnsenseClientAdapter_SearchHostOverrides_Call {
	_c.Call.Return(searchHostOverrideResponse, err)
	return _c
}

func (_c *MockOpnsenseClientAdapter_SearchHostOverrides_Call) RunAndReturn(run func(ctx context.Context) (*unbound.SearchHostOverrideResponse, error)) *MockOpnsenseClientAdapter_SearchHostOverrides_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateHostOverride provides a mock function for the type MockOpnsenseClientAdapter
func (_mock *MockOpnsenseClientAdapter) UpdateHostOverride(ctx context.Context, uuid string, req *unbound.HostOverride) error {
	ret := _mock.Called(ctx, uuid, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateHostOverride")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *unbound.HostOverride) error); ok {
		r0 = returnFunc(ctx, uuid, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOpnsenseClientAdapter_UpdateHostOverride_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateHostOverride'
type MockOpnsenseClientAdapter_UpdateHostOverride_Call struct {
	*mock.Call
}

// UpdateHostOverride is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
//   - req *unbound.HostOverride
func (_e *MockOpnsenseClientAdapter_Expecter) UpdateHostOverride(ctx interface{}, uuid interface{}, req interface{}) *MockOpnsenseClientAdapter_UpdateHostOverride_Call {
	return &MockOpnsenseClientAdapter_UpdateHostOverride_Call{Call: _e.mock.On("UpdateHostOverride", ctx, uuid, req)}
}

func (_c *MockOpnsenseClientAdapter_UpdateHostOverride_Call) Run(run func(ctx context.Context, uuid string, req *unbound.HostOverride)) *MockOpnsenseClientAdapter_UpdateHostOverride_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *unbound.HostOverride
		if args[2] != nil {
			arg2 = args[2].(*unbound.HostOverride)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOpnsenseClientAdapter_UpdateHostOverride_Call) Return(err error) *MockOpnsenseClientAdapter_UpdateHostOverride_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOpnsenseClientAdapter_UpdateHostOverride_Call) RunAndReturn(run func(ctx context.Context, uuid string, req *unbound.HostOverride) error) *MockOpnsenseClientAdapter_UpdateHostOverride_Call {
	_c.Call.Return(run)
	return _c
}
