// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockservices

import (
	"context"

	"github.com/cenk1cenk2/external-dns-webhook-opnsense/internal/services/opnsense"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClientAdapter creates a new instance of MockClientAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientAdapter {
	mock := &MockClientAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClientAdapter is an autogenerated mock type for the ClientAdapter type
type MockClientAdapter struct {
	mock.Mock
}

type MockClientAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientAdapter) EXPECT() *MockClientAdapter_Expecter {
	return &MockClientAdapter_Expecter{mock: &_m.Mock}
}

// CheckUnboundService provides a mock function for the type MockClientAdapter
func (_mock *MockClientAdapter) CheckUnboundService(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CheckUnboundService")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientAdapter_CheckUnboundService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckUnboundService'
type MockClientAdapter_CheckUnboundService_Call struct {
	*mock.Call
}

// CheckUnboundService is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClientAdapter_Expecter) CheckUnboundService(ctx interface{}) *MockClientAdapter_CheckUnboundService_Call {
	return &MockClientAdapter_CheckUnboundService_Call{Call: _e.mock.On("CheckUnboundService", ctx)}
}

func (_c *MockClientAdapter_CheckUnboundService_Call) Run(run func(ctx context.Context)) *MockClientAdapter_CheckUnboundService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClientAdapter_CheckUnboundService_Call) Return(err error) *MockClientAdapter_CheckUnboundService_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientAdapter_CheckUnboundService_Call) RunAndReturn(run func(ctx context.Context) error) *MockClientAdapter_CheckUnboundService_Call {
	_c.Call.Return(run)
	return _c
}

// ReconfigureService provides a mock function for the type MockClientAdapter
func (_mock *MockClientAdapter) ReconfigureService(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ReconfigureService")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientAdapter_ReconfigureService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReconfigureService'
type MockClientAdapter_ReconfigureService_Call struct {
	*mock.Call
}

// ReconfigureService is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClientAdapter_Expecter) ReconfigureService(ctx interface{}) *MockClientAdapter_ReconfigureService_Call {
	return &MockClientAdapter_ReconfigureService_Call{Call: _e.mock.On("ReconfigureService", ctx)}
}

func (_c *MockClientAdapter_ReconfigureService_Call) Run(run func(ctx context.Context)) *MockClientAdapter_ReconfigureService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClientAdapter_ReconfigureService_Call) Return(err error) *MockClientAdapter_ReconfigureService_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientAdapter_ReconfigureService_Call) RunAndReturn(run func(ctx context.Context) error) *MockClientAdapter_ReconfigureService_Call {
	_c.Call.Return(run)
	return _c
}

// UnboundCreateHostOverride provides a mock function for the type MockClientAdapter
func (_mock *MockClientAdapter) UnboundCreateHostOverride(ctx context.Context, req *opnsense.UnboundHostOverride) (string, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UnboundCreateHostOverride")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *opnsense.UnboundHostOverride) (string, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *opnsense.UnboundHostOverride) string); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *opnsense.UnboundHostOverride) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientAdapter_UnboundCreateHostOverride_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnboundCreateHostOverride'
type MockClientAdapter_UnboundCreateHostOverride_Call struct {
	*mock.Call
}

// UnboundCreateHostOverride is a helper method to define mock.On call
//   - ctx context.Context
//   - req *opnsense.UnboundHostOverride
func (_e *MockClientAdapter_Expecter) UnboundCreateHostOverride(ctx interface{}, req interface{}) *MockClientAdapter_UnboundCreateHostOverride_Call {
	return &MockClientAdapter_UnboundCreateHostOverride_Call{Call: _e.mock.On("UnboundCreateHostOverride", ctx, req)}
}

func (_c *MockClientAdapter_UnboundCreateHostOverride_Call) Run(run func(ctx context.Context, req *opnsense.UnboundHostOverride)) *MockClientAdapter_UnboundCreateHostOverride_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *opnsense.UnboundHostOverride
		if args[1] != nil {
			arg1 = args[1].(*opnsense.UnboundHostOverride)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientAdapter_UnboundCreateHostOverride_Call) Return(s string, err error) *MockClientAdapter_UnboundCreateHostOverride_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockClientAdapter_UnboundCreateHostOverride_Call) RunAndReturn(run func(ctx context.Context, req *opnsense.UnboundHostOverride) (string, error)) *MockClientAdapter_UnboundCreateHostOverride_Call {
	_c.Call.Return(run)
	return _c
}

// UnboundDeleteHostOverride provides a mock function for the type MockClientAdapter
func (_mock *MockClientAdapter) UnboundDeleteHostOverride(ctx context.Context, uuid string) error {
	ret := _mock.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for UnboundDeleteHostOverride")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, uuid)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientAdapter_UnboundDeleteHostOverride_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnboundDeleteHostOverride'
type MockClientAdapter_UnboundDeleteHostOverride_Call struct {
	*mock.Call
}

// UnboundDeleteHostOverride is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *MockClientAdapter_Expecter) UnboundDeleteHostOverride(ctx interface{}, uuid interface{}) *MockClientAdapter_UnboundDeleteHostOverride_Call {
	return &MockClientAdapter_UnboundDeleteHostOverride_Call{Call: _e.mock.On("UnboundDeleteHostOverride", ctx, uuid)}
}

func (_c *MockClientAdapter_UnboundDeleteHostOverride_Call) Run(run func(ctx context.Context, uuid string)) *MockClientAdapter_UnboundDeleteHostOverride_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientAdapter_UnboundDeleteHostOverride_Call) Return(err error) *MockClientAdapter_UnboundDeleteHostOverride_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientAdapter_UnboundDeleteHostOverride_Call) RunAndReturn(run func(ctx context.Context, uuid string) error) *MockClientAdapter_UnboundDeleteHostOverride_Call {
	_c.Call.Return(run)
	return _c
}

// UnboundSearchHostOverrides provides a mock function for the type MockClientAdapter
func (_mock *MockClientAdapter) UnboundSearchHostOverrides(ctx context.Context, req *opnsense.UnboundSearchHostOverrideRequest) (*opnsense.UnboundSearchHostOverrideResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UnboundSearchHostOverrides")
	}

	var r0 *opnsense.UnboundSearchHostOverrideResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *opnsense.UnboundSearchHostOverrideRequest) (*opnsense.UnboundSearchHostOverrideResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *opnsense.UnboundSearchHostOverrideRequest) *opnsense.UnboundSearchHostOverrideResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*opnsense.UnboundSearchHostOverrideResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *opnsense.UnboundSearchHostOverrideRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientAdapter_UnboundSearchHostOverrides_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnboundSearchHostOverrides'
type MockClientAdapter_UnboundSearchHostOverrides_Call struct {
	*mock.Call
}

// UnboundSearchHostOverrides is a helper method to define mock.On call
//   - ctx context.Context
//   - req *opnsense.UnboundSearchHostOverrideRequest
func (_e *MockClientAdapter_Expecter) UnboundSearchHostOverrides(ctx interface{}, req interface{}) *MockClientAdapter_UnboundSearchHostOverrides_Call {
	return &MockClientAdapter_UnboundSearchHostOverrides_Call{Call: _e.mock.On("UnboundSearchHostOverrides", ctx, req)}
}

func (_c *MockClientAdapter_UnboundSearchHostOverrides_Call) Run(run func(ctx context.Context, req *opnsense.UnboundSearchHostOverrideRequest)) *MockClientAdapter_UnboundSearchHostOverrides_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *opnsense.UnboundSearchHostOverrideRequest
		if args[1] != nil {
			arg1 = args[1].(*opnsense.UnboundSearchHostOverrideRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientAdapter_UnboundSearchHostOverrides_Call) Return(unboundSearchHostOverrideResponse *opnsense.UnboundSearchHostOverrideResponse, err error) *MockClientAdapter_UnboundSearchHostOverrides_Call {
	_c.Call.Return(unboundSearchHostOverrideResponse, err)
	return _c
}

func (_c *MockClientAdapter_UnboundSearchHostOverrides_Call) RunAndReturn(run func(ctx context.Context, req *opnsense.UnboundSearchHostOverrideRequest) (*opnsense.UnboundSearchHostOverrideResponse, error)) *MockClientAdapter_UnboundSearchHostOverrides_Call {
	_c.Call.Return(run)
	return _c
}

// UnboundUpdateHostOverride provides a mock function for the type MockClientAdapter
func (_mock *MockClientAdapter) UnboundUpdateHostOverride(ctx context.Context, uuid string, req *opnsense.UnboundHostOverride) error {
	ret := _mock.Called(ctx, uuid, req)

	if len(ret) == 0 {
		panic("no return value specified for UnboundUpdateHostOverride")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *opnsense.UnboundHostOverride) error); ok {
		r0 = returnFunc(ctx, uuid, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientAdapter_UnboundUpdateHostOverride_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnboundUpdateHostOverride'
type MockClientAdapter_UnboundUpdateHostOverride_Call struct {
	*mock.Call
}

// UnboundUpdateHostOverride is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
//   - req *opnsense.UnboundHostOverride
func (_e *MockClientAdapter_Expecter) UnboundUpdateHostOverride(ctx interface{}, uuid interface{}, req interface{}) *MockClientAdapter_UnboundUpdateHostOverride_Call {
	return &MockClientAdapter_UnboundUpdateHostOverride_Call{Call: _e.mock.On("UnboundUpdateHostOverride", ctx, uuid, req)}
}

func (_c *MockClientAdapter_UnboundUpdateHostOverride_Call) Run(run func(ctx context.Context, uuid string, req *opnsense.UnboundHostOverride)) *MockClientAdapter_UnboundUpdateHostOverride_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *opnsense.UnboundHostOverride
		if args[2] != nil {
			arg2 = args[2].(*opnsense.UnboundHostOverride)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClientAdapter_UnboundUpdateHostOverride_Call) Return(err error) *MockClientAdapter_UnboundUpdateHostOverride_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientAdapter_UnboundUpdateHostOverride_Call) RunAndReturn(run func(ctx context.Context, uuid string, req *opnsense.UnboundHostOverride) error) *MockClientAdapter_UnboundUpdateHostOverride_Call {
	_c.Call.Return(run)
	return _c
}
